policy_checkpoint_path: policy/policy47_7.pt
policy_stand_path: policy/policy_stand3.pt
control_dt: 0.005
policy_dt: 0.02
physics_dt: 0.0005
cutoff_freq: 200
num_joints: 12
num_actions: 12
action_scale: 0.25
action_limit_lower: -10000
action_limit_upper: 10000
num_observations: 47
history_length: 0
gui/control_password: 1234

joints:
- hip_yaw_left
- hip_yaw_right
- hip_roll_left
- hip_roll_right
- hip_pitch_left
- hip_pitch_right
- knee_left
- knee_right
- ankle_pitch_left
- ankle_pitch_right
- ankle_roll_left
- ankle_roll_right

joint_kp:
# - 240.0
# - 240.0
# - 240.0
# - 240.0
# - 100.0
# - 100.0
# - 100.0
# - 100.0
# - 25.0
# - 25.0
# - 25.0
# - 25.0
- 240.0
- 240.0
- 240.0
- 240.0
- 50.0
- 50.0
- 20.0
- 20.0
- 10.0
- 10.0
- 10.0
- 10.0

joint_kd:
# - 5.0
# - 5.0
# - 5.0
# - 5.0
# - 2.5
# - 2.5
# - 2.5
# - 2.5
# - 1.0
# - 1.0
# - 1.0
# - 1.0
- 5.0
- 5.0
- 5.0
- 5.0
- 1.8
- 1.8
- 1.1
- 1.1
- 1.0
- 1.0
- 1.0
- 1.0

effort_limits:
- 40.0
- 40.0
- 40.0
- 40.0
- 60.0
- 60.0
- 60.0
- 60.0
- 6.0
- 6.0
- 6.0
- 6.0

default_joint_positions:
- 0.0
- 0.0
- 0.0
- 0.0
- -0.2
- -0.2
- 0.4
- 0.4
- -0.3
- -0.3
- 0.0
- 0.0

joint_zero_positions:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0

joint_reset_positions:
- 0.0
- 0.0
- -0.2
- 0.4
- -0.3
- 0.0
- 0.0
- 0.0
- -0.2
- 0.4
- -0.3
- 0.0

default_base_position:
- 0.0
- 0.0
- 0.77

action_indices:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11

joint_states/names:
- hip_yaw_left
- hip_roll_left
- hip_pitch_left
- knee_left
- ankle_pitch_left
- ankle_roll_left
- hip_yaw_right
- hip_roll_right
- hip_pitch_right
- knee_right
- ankle_pitch_right
- ankle_roll_right

can0.port: can1
can1.port: can2

# Joint position limits from MJCF (radians)
# Order: hip_yaw_left, hip_yaw_right, hip_roll_left, hip_roll_right,
#        hip_pitch_left, hip_pitch_right, knee_left, knee_right,
#        ankle_pitch_left, ankle_pitch_right, ankle_roll_left, ankle_roll_right
safety_layer.joint_pos_limit_lower:
- -3 #-0.698132  # hip_yaw_left
- -3 #-1.5708    # hip_yaw_right
- -3 #-0.698132  # hip_roll_left
- -3 #-1.5708    # hip_roll_right
- -3 #-1.8326    # hip_pitch_left
- -3 #-1.8326    # hip_pitch_right
- -3 #-0.1        # knee_left
- -3 #-0.1        # knee_right
- -3 #-1.22173   # ankle_pitch_left
- -3 #-1.22173   # ankle_pitch_right
- -3 #-0.663225  # ankle_roll_left
- -3 #-0.523599  # ankle_roll_right

safety_layer.joint_pos_limit_upper:
- 3 #1.5708     # hip_yaw_left
- 3 #0.698132   # hip_yaw_right
- 3 #1.5708     # hip_roll_left
- 3 #0.872665   # hip_roll_right
- 3 #0.523599   # hip_pitch_left
- 3 #0.523599   # hip_pitch_right
- 3 #2.1293     # knee_left
- 3 #2.1293     # knee_right
- 3 #1.0472     # ankle_pitch_left
- 3 #1.0472     # ankle_pitch_right
- 3 #0.523599   # ankle_roll_left
- 3 #0.663225   # ankle_roll_right
